---
galaxy_info:
  author: Alexander Yarmolinskiy
  description: Ansible role for Apache NiFi installation.
  license: MIT
  min_ansible_version: 2.0
  version: 2.0.1
dependencies:
  - sysctl-configure
