---
- name: Copy NiFi systemd unit
  template:
    src: "nifi.service.j2"
    dest: "/etc/systemd/system/nifi.service"
    mode: 0644
  become: true

- name: Start NiFi
  systemd:
    state: started
    enabled: yes
    name: "nifi"
    daemon_reload: yes
  become: true
