---
- name: Stop NiFi
  systemd:
    state: stopped
    enabled: no
    name: "nifi"
  become: true

- name: Remove Java
  yum:
    name: "{{ java }}"
    state: absent
    autoremove: yes
  become: true

- name: Remove Nifi directory
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ nifi_root }}/nifi-{{ nifi_version }}"
    - "{{ nifi_root }}/nifi-toolkit-{{ nifi_version }}"
  become: true

- name: Remove {{ nifi_user }} user
  user:
    name: "{{ nifi_user }}"
    state: absent
  become: true

- name: Remove {{ nifi_group }} group
  group:
    name: "{{ nifi_group }}"
    state: absent
  become: true
